### ISSUE TITLE
IOS the permission window disappears very quickly

### ISSUE THREAD

**Issue by Gashington** [Web3Auth/web3auth-react-native-sdk#10]
I am using your library as in your example. When I press the login button, a window pops up and disappears after a second. Therefore, the user cannot accept the permission and continue with the authentication process. In Xcode console I got this warning
`Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior (<SFAuthenticationViewController: 0x7fb29d83ea00>)`

**Comment by chaitanyapotti** [comment]
This should be fixed in the latest version already
