### ISSUE TITLE
React Native Tutorial incomplete

### ISSUE THREAD

**Issue by awcchungster** [Web3Auth/web3auth-react-native-sdk#12]
Hi Web3auth team,

I'm building [RealityCoin](https://www.realitycoin.org). It uses react native and I want to test the web3auth integration to simplify user login.

I found a few issues with the [tutorial](https://docs.web3auth.io/guides/openlogin-react-native).

- [x] Conversion from Web3auth private key doesn't convert to Solana TweetNacl compatible keys
- [x] there's no discussion of whitelist in the tutorials. I ran into the error in command line and then fixed it manually. Allowlist is a better term
- [x] Package name changed without updating docs / instructions

**Comment by awcchungster** [comment]
@chaitanyapotti @yashovardhan

**Comment by chaitanyapotti** [comment]
Hi,
the docs have been updated now
https://docs.web3auth.io/api-reference/react-native/choosesdk
We've already added https://docs.web3auth.io/api-reference/android/setting-up#configuration docs about whitelisting here
