### ISSUE TITLE
Couldn't able to integrate this successfully on RN 0.63.4

### ISSUE THREAD

**Issue by LucasWili** [Web3Auth/web3auth-react-native-sdk#18]
RN version - 0.63.4
Node version - v17.5.0

On IOS Xcode returns **"Compiling for iOS 10.0, but module 'Web3Auth' has a minimum deployment target of iOS 12.0:"** So had to manually change the deployment target into 12 every time. and then it builds successfully but when trying to run on the emulator it returns "Undefined symbol : (extension in foundation) Swift.StringProtocol.appending". I tried this one as well [comment](https://github.com/mxcl/PromiseKit/issues/1059#issuecomment-493925940) but still issue remains

**Comment by chaitanyapotti** [comment]
Please check now
