### ISSUE TITLE
Web3auth login in-app browser flow ends with Torus support chatbot

### ISSUE THREAD

**Issue by CallbackDan** [Web3Auth/web3auth-react-native-sdk#32]
Hi

I'm using the React Native SDK (3.1.0) to login in with a social login provider (Apple / Google). 

When I call .login() the in-app browser opens fine and lets me sign in with either Apple or Google, but after a redirect or two I'm taken to the Torus support chatbot page (picture attached). This confuses our users.

If an error caused this behaviour, can it close the in-app browser and throw an error, rather than redirecting to this page?

Is there a fix for this? Maybe a parameter that I can pass into the initialisation object?

Thank you.

![IMG_3033](https://user-images.githubusercontent.com/106639454/195769398-0bdd400b-d89f-48c6-a61c-fdba2b885b57.jpg)

**Comment by chaitanyapotti** [comment]
This means some error occured in the app.
Please use `chrome://inspect` to debug and send us the logs.
Also, pls update to the latest version of `expo-web-browser` or `react-native-web-browser` package

**Comment by chaitanyapotti** [comment]
This should be fixed in v4. Pls upgrade
