### ISSUE TITLE
How to do JWT login properly with React Native SDK?

### ISSUE THREAD

**Issue by nayuki-passthetest** [Web3Auth/web3auth-react-native-sdk#33]
I'm trying to use Web3Auth with the combination of Firebase Auth.

At first, I used to Google sign-in and Firebase Auth to get JWT token.
Next, I passed token to Web3Auth login on the following code:

```
const newState = await web3auth.login({
  loginProvider: LOGIN_PROVIDER.JWT,
  redirectUrl: '<schema>://openlogin',
  extraLoginOptions: {
    additionalParams: {
      id_token: <token>,
    },
  },
});
```

However, after the browser opens, it stops at a white screen like this.
![image](https://user-images.githubusercontent.com/34227759/196075062-44bd83bd-b4f6-4914-9872-33028e655f2b.png)

**Comment by maxhui9527** [comment]
I am facing the same issue, anyone can give some solution or insight here?

**Comment by shahbaz17** [comment]
Please look at the updated code https://web3auth.io/docs/sdk/react-native/custom-authentication#extraloginoptions-for-special-login-methods

```js
const web3auth = new Web3Auth(WebBrowser, {
  clientId: "YOUR_CLIENT_ID", // web3auth's client id
  network: Network.TESTNET,
  loginConfig: {
    jwt: {
      verifier: "verifier-name", // get it from web3auth dashboard
      typeOfLogin: TypeOfLogin.JWT,
      name: "Custom Login with JWT",
      clientId: "YOUR_CLIENT_ID", // web3auth's client id
    },
  },
});
web3auth.login({
  loginProvider: LoginProvider.JWT,
  redirectUrl: resolvedRedirectUrl,
  extraLoginOptions: {
    domain: "example.com", // domain of your app backend
    id_token: "your JWT token",
  },
});
```

cc @maxhui9527 @nayuki-passthetest

**Comment by maxhui9527** [comment]
> Please look at the updated code https://web3auth.io/docs/sdk/react-native/custom-authentication#extraloginoptions-for-special-login-methods
> 
> ```js
> const web3auth = new Web3Auth(WebBrowser, {
>   clientId: "YOUR_CLIENT_ID", // web3auth's client id
>   network: Network.TESTNET,
>   loginConfig: {
>     jwt: {
>       verifier: "verifier-name", // get it from web3auth dashboard
>       typeOfLogin: TypeOfLogin.JWT,
>       name: "Custom Login with JWT",
>       clientId: "YOUR_CLIENT_ID", // web3auth's client id
>     },
>   },
> });
> web3auth.login({
>   loginProvider: LoginProvider.JWT,
>   redirectUrl: resolvedRedirectUrl,
>   extraLoginOptions: {
>     domain: "example.com", // domain of your app backend
>     id_token: "your JWT token",
>   },
> });
> ```
> 
> cc @maxhui9527 @nayuki-passthetest

Yeah, it works.  One extra question, how can I hide the popup modal, just verify in background?

**Comment by shahbaz17** [comment]
@maxhui9527 

Which popup modal are we talking here? Can you share the screenshot?

**Comment by chaitanyapotti** [comment]
This should be fixed in v4. Pls upgrade
