### ISSUE TITLE
OpenloginReactNativeSdk.init is not a function

### ISSUE THREAD

**Issue by titocosta** [Web3Auth/web3auth-react-native-sdk#4]
When running the demo with React Native, I get a 
```
TypeError: _openloginReactNativeSdk.default.init is not a function. (In '_openloginReactNativeSdk.default.init(openLoginConfig)', '_openloginReactNativeSdk.default.init' is undefined)

```

**Comment by DanyylSocol** [comment]
> When running the demo with React Native, I get a
> 
> ```
> TypeError: _openloginReactNativeSdk.default.init is not a function. (In '_openloginReactNativeSdk.default.init(openLoginConfig)', '_openloginReactNativeSdk.default.init' is undefined)
> ```

Same error, do you have sollution?

**Comment by chaitanyapotti** [comment]
This should be fixed in the latest version

**Comment by jeffhu1** [comment]
Hi, I still have this issue
