### ISSUE TITLE
Unable to detect device share error

### ISSUE THREAD

**Issue by zachdorcinville21** [Web3Auth/web3auth-react-native-sdk#50]
This error page is sometimes shown during the authentication process:
![telegram-cloud-photo-size-1-5039582087186852693-y](https://user-images.githubusercontent.com/16417769/212998801-83893358-9a9c-4d99-b173-e44b2e97d103.jpg)

It states that the user needs to be on Google Chrome, but this user was already on Chrome. Additionally, we don't want any users to have to lower their security settings to mitigate this issue. Is there anything we can do to ensure we don't get this error page during log in/sign up? This issue has also popped up on React Native.

SDK versions (web):
`
"@web3auth/base": "^4.0.0-alpha.0",
    "@web3auth/core": "^4.0.0-alpha.0",
    "@web3auth/metamask-adapter": "^4.0.0-alpha.0",
    "@web3auth/openlogin-adapter": "^4.0.0-alpha.0",
    "@web3auth/web3auth": "^2.1.3",
`

SDK versions (React Native):
`
"@web3auth/react-native-sdk": "^3.3.0",
    "@web3auth/web3auth": "^2.1.2",
`

**Comment by YZhenY** [comment]
Do you have logs for this issue?

**Comment by yashovardhan** [comment]
Please update your packages.

`"@web3auth/base": "^4.0.0-alpha.0", "@web3auth/core": "^4.0.0-alpha.0", "@web3auth/metamask-adapter": "^4.0.0-alpha.0", "@web3auth/openlogin-adapter": "^4.0.0-alpha.0", "@web3auth/web3auth": "^2.1.3"` - these were all older releases, latest SDKs are on 4.6.x

Please check here: https://github.com/web3auth/web3auth-web

also the react native SDK is meant to be stand alone. Please do not club it with any web packages, it only cause errors. Please follow our example repository: https://github.com/web3auth/examples

Please open up a new issue when this error occurs again in the latest packages.
