### ISSUE TITLE
Auth0 email passwordless not working

### ISSUE THREAD

**Issue by tbosch82** [Web3Auth/web3auth-react-native-sdk#51]
`login` fails with a syntax error when `extraLoginOptions.redirect_uri` is set:

`[SyntaxError: JSON Parse error: Unexpected token: i]` 

If `extraLoginOptions.redirect_uri` is left undefined Auth0 social logins work fine, but when attempting to login with email passwordless an error is displayed: 

![image](https://user-images.githubusercontent.com/43397354/214908366-943aafef-45c4-44b8-9434-b0be06a7d558.png)

**Comment by chaitanyapotti** [comment]
This should be fixed in v4. Pls upgrade
