### ISSUE TITLE
v3.6.0 release we need urgently. there is no init function in v3.5.0

### ISSUE THREAD

**Issue by nftbigdev** [Web3Auth/web3auth-react-native-sdk#64]

**Comment by cocadev** [comment]
Any news here?

**Comment by nftbigdev** [comment]
Hey. Whats up in this package?

**Comment by GeorgeNiotis** [comment]
@michaellee8 can one of the contributors plz answer

**Comment by michaellee8** [comment]
> @michaellee8 can one of the contributors plz answer

I no longer works for Web3Auth, @chaitanyapotti please handle this issue, thx.

**Comment by GeorgeNiotis** [comment]
@chaitanyapotti plz can someone answer
The code is there you just need to republish the version with the correct code
Currently the examples nor the docs corresponds to the released version

**Comment by GeorgeNiotis** [comment]
@chaitanyapotti
Plz can we have an answer regarding this issue otherwise you set the project as stale.

**Comment by arch1995** [comment]
We have a released a new version for this. Pls update
