### ISSUE TITLE
Setting `curve` parameter in `login` has no effect

### ISSUE THREAD

**Issue by grabbou** [Web3Auth/web3auth-react-native-sdk#65]
Hey!

I wanted to change the curve for the public key encoded in the `idToken` from SECP256K1 to ED25519, and unfortunately, it has no effect. No matter the `curve` string passed, the end result is always the same (which is `SECP256K1`).

PS. Would it be possible actually to specify an array in the future to receive both? I quite appreciate the fact you return both private keys on React Native, which is great for multi-chain dapps that work on both Eth and Solana at the same time.

Having the same for `idToken` would be super useful too!

**Comment by chaitanyapotti** [comment]
This should be fixed in v4. Pls upgrade
