### ISSUE TITLE
Move browserify polyfills from `peer` to `dev` dependencies

### ISSUE THREAD

**Issue by grabbou** [Web3Auth/web3auth-react-native-sdk#66]
https://github.com/Web3Auth/web3auth-react-native-sdk/blob/42c880471728e5b2dfc820f09575751019a77116/package.json#L48-L49

After searching the codebase, they're used in the examples. It shouldn't be part of peer dependencies to avoid warnings and implicit installations by some packages.

Also, there are alternative polyfills, especially for Expo users (such as `expo-crypto`) that may be preferred over `crypto-browserify` for performance and stability.

**Comment by arch1995** [comment]
Pls update to v4.
