### ISSUE TITLE
Could not validate redirect url

### ISSUE THREAD

**Issue by bachlongkocanh** [Web3Auth/web3auth-react-native-sdk#67]
Hi team
I am having issues with redirect. I have installed the SDK according to the instructions, but when I try to login, I get an error message saying "Could not validate redirect URL, please whitelist your redirect URL..." even though I have added my deeplink URL to the whitelist of my project. Please help me troubleshoot this issue.

- React native: 0.69.5
- React: 18.0.0
```
const web3auth = new Web3Auth(WebBrowser, {
  clientId,
  network: OPENLOGIN_NETWORK.TESTNET, // or other networks
  redirectUrl: resolvedRedirectUrl,
});

 web3auth.login({
        loginProvider: LOGIN_PROVIDER.JWT,
        redirectUrl: resolvedRedirectUrl,
        mfaLevel: 'default',
        extraLoginOptions: {
          IdleDeadline_token:'eyJhbG....',
          verifierIdField: 'sub',
        },
      });

```
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-03-06 at 22 38 07](https://user-images.githubusercontent.com/28125294/223157794-7112b871-7cad-413f-aa4c-e18c2a0d0d6f.png)

**Comment by arch1995** [comment]
Pls update to v4
