### ISSUE TITLE
Request for Detailed Migration Guide from SDK 4.0 to 5.0

### ISSUE THREAD

**Issue by NandyBa** [Web3Auth/web3auth-react-native-sdk#79]
Hello 👋,

I hope this message finds you well. Firstly, thank you for your continued work on this SDK.

We have noticed that moving from SDK version 4.0 to 5.0 brings several changes. For a smoother transition, it would be immensely helpful if a detailed change log or a step-by-step migration guide could be provided in the release notes or README.

Currently, developers might find themselves navigating through the codebase to understand the changes and updates. A comprehensive guide could expedite the upgrade process and mitigate potential integration issues.

Thank you for considering this request. We look forward to the continued development and enhancement of the SDK.

Best regards,

**Comment by chaitanyapotti** [comment]
https://web3auth.io/docs/pnp/migration-guides/rn-v4-to-v5
