### ISSUE TITLE
{“name”:“OpenloginError”,“code”:5114,“message”:“Login failed, SessionId is missing”} when try to authenticate user via Twitter (X)

### ISSUE THREAD

**Issue by BondarevskiyE** [Web3Auth/web3auth-react-native-sdk#98]
Hi!
Need help with connecting twitter (X) via web3Auth

Authorization via Google works fine, but via Twitter Im getting error {“name”:“OpenloginError”,“code”:5114,“message”:“Login failed, SessionId is missing”}.
In the Auth0 console I see that auth passed ok, but after login sdk give me the error

After research I found out that the place throwing the error is here:
/[@Web3Auth](https://web3auth.io/community/u/web3auth)/react-native-sdk/dist/lib.cjs/Web3Auth.js , method login, 150 line
```
const {
  sessionId,
  sessionNamespace,
  error
 } = utils.getHashQueryParams(result.url);
if (error || !sessionId) {
   throw errors.LoginError.loginFailed(error || “SessionId is missing”);
}
```

getHashQueryParams doesn’t give sessionId because result.url doesn’t include sessionId (after encoding it has tokens and user info). 

Maybe the problem is in Auth0 misconfiguration, there is nothing to configurate in Auth0 though

Here my code

```
const SdkInitParams = {
  clientId: ‘my-clientId’,
  network: OPENLOGIN_NETWORK.SAPPHIRE_DEVNET,
  redirectUrl,
  loginConfig: {
    twitter: {
      verifier: ‘twittermobile’,
      typeOfLogin: LOGIN_PROVIDER.TWITTER,
      clientId: ‘clientId’,
   },
 },
};

web3auth.login({
    loginProvider: LOGIN_PROVIDER.TWITTER
    redirectUrl,
    extraLoginOptions: {
       domain: ‘domain’,
       verifierIdField: ‘sub’,
       connection: LOGIN_PROVIDER.TWITTER,
    },
});
```

please help

**Comment by alhxji** [comment]
Any fix for this yet @ebondarevskii
